version: 2

project_name: git-id

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: git-id
    main: .
    binary: git-id
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: git-id-archive
    ids:
      - git-id
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*
      - docs/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^style:"
      - "^refactor:"
      - "^ci:"
      - "^build:"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "Merge branch"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Documentation
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: Other
      order: 999

release:
  github:
    owner: silverlightning926
    name: git-id
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
  header: |
    ## Git Profile Manager (git-id) v{{ .Version }}

    A CLI tool for managing multiple Git profiles.
  footer: |
    ## Installation

    ### Using Go
    ```bash
    go install github.com/silverlightning926/git-id@latest
    ```

    ### Using Homebrew (macOS/Linux)
    ```bash
    brew install --cask silverlightning926/tap/git-id
    ```

    ### Using Docker
    ```bash
    docker run --rm ghcr.io/silverlightning926/git-id:latest
    ```

    ### Using downloaded binaries
    Download the appropriate binary for your system from the assets below.

homebrew_casks:
  - name: git-id
    repository:
      owner: silverlightning926
      name: homebrew-tap
    homepage: https://github.com/silverlightning926/git-id
    description: "A CLI tool for managing multiple Git profiles"
    license: MIT
    directory: Casks
    conflicts:
      - formula: git-id
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-id"]
          end
          system_command "/bin/ln", args: ["-sf", "#{staged_path}/git-id", "#{HOMEBREW_PREFIX}/bin/gid"]

dockers:
  - image_templates:
      - "ghcr.io/silverlightning926/git-id:latest"
      - "ghcr.io/silverlightning926/git-id:{{ .Tag }}"
      - "ghcr.io/silverlightning926/git-id:v{{ .Major }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
